### ISSUE TITLE
about training view selection

### ISSUE THREAD

**Issue by zhanghaoyu816** [ForMyCat/SparseGS#14]
Thanks for your nice project. I'm curious about what method or criteria you use to select 12 training views of mipnerf360 dataset. I want to select sparse training views in some complex scene such as mipnerf360, scannet or tanks&temples so that these views can cover most of the whole scene with less overlap between views. So do you have any suggestions for this? Or could you please provide the code for data selection? Thanks.

**Comment by ForMyCat** [comment]
Since 12-view is too sparse for 360 scene, at this stage we only mannually select views with as much coverage as possible.
