### ISSUE TITLE
Questions about installing submodules

### ISSUE THREAD

**Issue by yyn27** [ForMyCat/SparseGS#15]
Hi everyone 
I always met this problem when installing diff-gaussian-rasterization-softmax and  simple-knn.
Do you have any solutions? (I have tried to change the version of cudatoolkit to 11.8)
<img width="1026" alt="image" src="https://github.com/ForMyCat/SparseGS/assets/131854295/46fe2d77-aa19-40db-b249-f50c9501e1e8">

**Comment by VENTAXR** [comment]
do not install diff-gaussian-rasterization-softmax..
how to build & install??

**Comment by VENTAXR** [comment]
only.. linux??

**Comment by sairisheek** [comment]
What is the specific build error you are facing? Please try to search for the keyword "error" and show the specific stacktraces.

**Comment by destroy314** [comment]
I got `subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.` when building diff-gaussian-rasterization-softmax, and fix it by copying a [glm](https://github.com/g-truc/glm/tree/5c46b9c07008ae65cb81ab79cd677ecc1934b903) folder into `third_party`.
