### ISSUE TITLE
Questions about calculate metrics

### ISSUE THREAD

**Issue by Starak-x** [ForMyCat/SparseGS#16]
Hi, Haolin. I noticed that the excluded file(training images) is divided into two calculations, without calculating half of it each time. Could you please explain the reasoning behind this operation?
![image](https://github.com/ForMyCat/SparseGS/assets/71073947/a39674e4-4928-4264-b776-1b2b1e74617b)

**Comment by ForMyCat** [comment]
Hi, it was due to memory constraints. We only had 24GB GPUs so it might throw OOM error if image resolutions are too high. So we had to split the eval into two halves.
