### ISSUE TITLE
(forward.cu -> calculating d_softmax) Why do need to subtract 0.3 from w in the code?

### ISSUE THREAD

**Issue by 18128381510** [ForMyCat/SparseGS#18]
I have a confusion. In the code(forward.cu), when calculating d_softmax(Equ. 4 in the paper),  it subtracts 0.3 from w. The original Equ. 4 in the paper does not have this subtraction of 0.3 from w. Why does the code subtract 0.3 from w?
```
forward.cu -> renderCUDA():

D += depp*w*exp(beta_k*(w-0.3f)); // Why do need to subtract 0.3 from w?
Z += w*exp(beta_k*(w-0.3f));

out_depth[pix_id] = log(D / Z + 1e-8f);
```

**Comment by sairisheek** [comment]
This is just for stability, dividing by exp(-0.3) in the numerator and denominator leaves the output unchanged.
