### ISSUE TITLE
About the parameter of training

### ISSUE THREAD

**Issue by Starak-x** [ForMyCat/SparseGS#19]
Hi, Haolin.  Could you please provide me with the training parameters or more training details?  I trained the 3DGS model as baseline and achieved an average PSNR of 14.69. When I trained your original code, I obtained an average PSNR of 16.42, both on the MipNerFR-360 dataset.

**Comment by ForMyCat** [comment]
The results are also dependent on the initial pointcloud. You can try using COLMAP MVS for a denser point cloud. Hyper-parameters are as shown on the repo page.
