### ISSUE TITLE
how to render the model

### ISSUE THREAD

**Issue by oscarmore2** [ForMyCat/SparseGS#20]
I have trained a model of my data. But when I tried to render it, it didn't process at all.
<img width="582" alt="image" src="https://github.com/user-attachments/assets/bfde4cec-19f7-4963-856a-5223931660ac">
the cmd just jump to next line. I could assure the path is correct.
<img width="648" alt="image" src="https://github.com/user-attachments/assets/2fa9984d-86fc-4a41-8c7e-b14e18aaeaf9">

**Comment by ForMyCat** [comment]
Your command seems to be correct. The rendered images should be in the checkpoint folder.
