### ISSUE TITLE
training SparseGS with car images

### ISSUE THREAD

**Issue by ansj11** [ForMyCat/SparseGS#4]
Your work is impressive and I have some questions. I am training SparseGS with 32 horizontal views of a car, and I want use this method to get better looking-down views. But the results are not so good, do you have any suggestions? Here are my images and results.

![image](https://github.com/ForMyCat/SparseGS/assets/24786133/6c175caf-4986-449b-8cdd-cde43bf5ffb6)
![image](https://github.com/ForMyCat/SparseGS/assets/24786133/ac8ec021-e41e-49e4-954b-f7b3eaf2f4db)

![image](https://github.com/ForMyCat/SparseGS/assets/24786133/58006520-7ac5-416c-9689-b41584ab8f38)
![image](https://github.com/ForMyCat/SparseGS/assets/24786133/220a7790-484c-428d-b2b9-f87c0cf12d6e)

**Comment by ForMyCat** [comment]
If this is the case, you can try playing with SDS hyperparameters, or sampling looking-down views (instead of the random sampling in my code) to apply the SDS loss.
