### ISSUE TITLE
about OOM

### ISSUE THREAD

**Issue by YZWYD** [ForMyCat/SparseGS#5]
Hello, thank you very much for open-sourcing this work. I encountered an out-of-memory issue when trying to reproduce it, as my device only has 8GB of CUDA memory. What should I modify to avoid this from happening?

**Comment by ForMyCat** [comment]
Try playing with the -r argument. (i.e. -r 8 will scale all the training images to 1/8 resolution) You can also try disabling SDS and Warping. 8G is a bit tight. I recommend you start with a lower resolution and add one component at a time to test. (depth Pearson loss --> floater pruning --> SDS --> Warping)

**Comment by YZWYD** [comment]
Thank you so much for your prompt reply! By the way, when you mentioned SDS and Warping in your response, are you referring to Diffusion Params and Depth Warping Loss parms? (I apologize for any ambiguity in my understanding due to my limited English proficiency.)

**Comment by ForMyCat** [comment]
Yes, sorry for the confusion. SDS uses Stable Diffusion as backbone and Depth Warping Loss can be viewed as a regularization term, hence the naming.

**Comment by YZWYD** [comment]
Thank you once again for your prompt response!  As a newcomer to the field of 3D vision, I am still becoming familiar with some of the terminology, which may have caused some communication barriers.  I apologize for any inconvenience.

**Comment by ForMyCat** [comment]
Don't worries! Thank you for your interest in our project! Feel free to open a new issue if you have further questions.
