### ISSUE TITLE
Question about pretrained stablediffusion model

### ISSUE THREAD

**Issue by zhanghaoyu816** [ForMyCat/SparseGS#8]
Hello, thanks a lot for your nice project.
I have a small question about the pretrained stable diffusion model. According to the error message the problem should be that the network can not be connected to the huggingface. 
![图片](https://github.com/ForMyCat/SparseGS/assets/60644792/4d71c066-fd11-4ea4-8bcc-377b0f5b028f)

So I try to download the model "stable-diffusion 2-1 base" locally. Should I download the "v2-1_768-ema-pruned.ckpt" or something else? And what should I do with the pretrained model?
![图片](https://github.com/ForMyCat/SparseGS/assets/60644792/5ddd3e39-7664-4d98-940f-27f9c4e9f481)

Cause I'm a beginner in this field , this question may be a little silly, thanks for your careful answer!

**Comment by ForMyCat** [comment]
Ah, I understand your problem. We use the official StableDiffusionPipeline from diffusers. Check out this link: [Official Documentation](https://huggingface.co/docs/diffusers/en/using-diffusers/loading), scroll down, there is a section telling you how to load local checkpoints. Hope this is helpful.

**Comment by zhanghaoyu816** [comment]
Thank you！I‘ll try it
